// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpv5J6uQHdfIJNkygqyZb7sKRfcikFC-o',
    appId: '1:720036659110:web:d3c632277becef865b1967',
    messagingSenderId: '720036659110',
    projectId: 'final-bike-b89cc',
    authDomain: 'final-bike-b89cc.firebaseapp.com',
    storageBucket: 'final-bike-b89cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDSAZN2Or1FKlU6qkAhow7nIAPMpoBYrI',
    appId: '1:720036659110:android:9ffd780bbf5304dd5b1967',
    messagingSenderId: '720036659110',
    projectId: 'final-bike-b89cc',
    storageBucket: 'final-bike-b89cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTc4aqLQTvBdt-nttMtba3PL7UoAU-J6g',
    appId: '1:720036659110:ios:38a1616aee55af1f5b1967',
    messagingSenderId: '720036659110',
    projectId: 'final-bike-b89cc',
    storageBucket: 'final-bike-b89cc.appspot.com',
    iosClientId: '720036659110-qqikt0n65fqmtq7akkggbcuh4js6e0rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeProject',
  );
}
